<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Error Handling</title>
	<script>
		// console.log(1)
		// console.log(2)
		// console.log(eval('Abhishek+Abhay'))
		// console.log(3)
		// console.log(4)
		// console.log(5)

		// Error Handling
		// try {
		// 	// Inside try, include those expression which are likely to give errors 
		// } catch (error) {
		// }

		// console.log(1)
		// console.log(2)
		// try {
		// 	console.log('Try')
		// 	console.log(eval('5+2'))
		// } catch (error) {
		// 	console.log('Catch: ' + error)
		// }
		// console.log(3)
		// console.log(4)
		// console.log(5)

		// console.log(1)
		// console.log(2)
		// try {
		// 	console.log('Try')
		// 	console.log(eval('Karishma + Shradha'))
		// } catch (error) {
		// 	console.log('Catch: ' + error)
		// } finally { // Regardless of any runtime errors, this block will always get executed
		// 	console.log('Finally')
		// }
		// console.log(3)
		// console.log(4)
		// console.log(5)


		// throw - User created error
		let input = -5

		console.log(1)
		console.log(2)
		try {
			console.log('Try')
			if(input < 0) {
				throw "Only 0 or positive numbers are allowed"
			}
			// factorial code here
		} catch (error) {
			console.log('Catch: ' + error)
		}
		console.log(3)
		console.log(4)
		console.log(5)
	</script>
</head>
<body>
	
</body>
</html>